"""create model credits

Revision ID: 59413fc4ac2a
Revises: daa8b58c6422
Create Date: 2025-10-10 12:40:53.813135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59413fc4ac2a'
down_revision: Union[str, Sequence[str], None] = 'daa8b58c6422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('annual_sales', sa.Float(), nullable=False),
    sa.Column('fiscal_year_closing', sa.String(), nullable=False),
    sa.Column('total_assets', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'REJECTED', name='status_enum'), nullable=False),
    sa.Column('pyme_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['pyme_id'], ['pymes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credits')
    # ### end Alembic commands ###
